version: "3"

services:
  api:
    container_name: shorty
    restart: unless-stopped
    build:
      context: ./Api
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "2000:2000"