GET {{url}}/api/v1/domains
Authorization: Bearer {{$auth.token("access-token")}}

###

POST {{url}}/api/v1/domains
Authorization: Bearer {{$auth.token("access-token")}}
Content-Type: application/json

{
  "value": "sh0.su"
}