GET http://localhost:2000/api/v1/domains
Authorization: Bearer {{$auth.token("access-token")}}

###

POST http://localhost:2000/api/v1/domains
Authorization: Bearer {{$auth.token("access-token")}}
Content-Type: application/json

{
  "value": "sh0.su"
}