GET http://localhost:2000/api/v1/links
Authorization: Bearer {{$auth.token("access-token")}}

###

GET http://localhost:2000/api/v1/links/ede725c6-aa14-44c5-823b-828fd881c79f
Authorization: Bearer {{$auth.token("access-token")}}

###
POST http://localhost:2000/api/v1/links
Authorization: Bearer {{$auth.token("access-token")}}
Content-Type: application/json

{
  "title": "123123wda1",
  "subdomain": "gooddfawds12",
  "domainUid": "178015e5-05c8-4d22-b122-030aacfc8d69",
  "url": "wg.dobroe22.keenetic.pro",
  "password": "123123"
}