GET {{url}}/api/v1/redirects/link?domain=sh0.su&path=ml6v1s

###

POST {{url}}/api/v1/redirects
Content-Type: application/json

{
  "os": "windows",
  "device": "mobile",
  "ip": "127.0.0.1",
  "userKey": "41c6e485-b373-4723-a31e-3ee767367fbd",
  "domain": "localhost:3001",
  "subdomain": "test",
  "path": "fcaz6p"
}