GET http://localhost:2000/api/v1/tags
Authorization: Bearer {{$auth.token("access-token")}}

###

PUT http://localhost:2000/api/v1/tags/bober
Authorization: Bearer {{$auth.token("access-token")}}
Content-Type: application/json

{
  "title": "12"
}

###

DELETE http://localhost:2000/api/v1/tags/daahs
Authorization: Bearer {{$auth.token("access-token")}}