name: "shorty-server"
version: "3.8"

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2000:2000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=kozodoy
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - KEYCLOAK_CLIENT=kozodoy-client
      - KEYCLOAK_REALM=kozodoy
      - KEYCLOAK_HOST=auth
      - KEYCLOAK_PORT=8180
    networks:
      - backend-network
    restart: always


  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=kozodoy'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    networks:
      - backend-network
    restart: always

  auth:
    image: quay.io/keycloak/keycloak:22.0.1
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --import-realm
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.migration.dir=/opt/keycloak/data/import"
      - "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
    volumes:
      - ./realms:/opt/keycloak/data/import
    networks:
      - backend-network

    restart: always

networks:
  backend-network: