GET {{url}}/api/v1/user/links
Authorization: Bearer {{$auth.token("access-token")}}

###

GET {{url}}/api/v1/user/links/6f7a1af1-03b1-493f-9e70-854136241c70
Authorization: Bearer {{$auth.token("access-token")}}

###

DELETE {{url}}/api/v1/user/links/f7d5833d-30b1-4065-91d4-2f2b8f8db11b
Authorization: Bearer {{$auth.token("access-token")}}

###

PUT {{url}}/api/v1/user/links/11b0f957-72c9-4c2e-ab55-87c45b30c098
Authorization: Bearer {{$auth.token("access-token")}}
Content-Type: application/json

{
  "title": "Untitled",
  "tags": [
    "it",
    "vk"
  ]
}

###

POST {{url}}/api/v1/user/links
Authorization: Bearer {{$auth.token("access-token")}}
Content-Type: application/json

{
  "title": "Untitled",
  "path": "94czwi",
  "subdomainUid": "2e0225b9-80bd-4a80-932a-7d2b3ef2d7f4",
  "domainUid": "e481ae10-a860-45f3-be75-f537c108162b",
  "url": "https://www.youtube.com/watch?v=GVTf9lLNnBU",
  "tags": []
}