GET {{url}}/api/v1/user/links
Authorization: Bearer {{$auth.token("access-token")}}

###

GET {{url}}/api/v1/user/links/6f7a1af1-03b1-493f-9e70-854136241c70
Authorization: Bearer {{$auth.token("access-token")}}

###

DELETE {{url}}/api/v1/user/links/e2dc74cd-e020-4c72-8736-38ca60942d61
Authorization: Bearer {{$auth.token("access-token")}}

###

PUT {{url}}/api/v1/user/links/11b0f957-72c9-4c2e-ab55-87c45b30c098
Authorization: Bearer {{$auth.token("access-token")}}
Content-Type: application/json

{
  "title": "Untitled",
  "tags": [
    "it",
    "vk"
  ],
  "password": ""
}

###

POST {{url}}/api/v1/user/links
Authorization: Bearer {{$auth.token("access-token")}}
Content-Type: application/json

{
  "title": "tests2",
  "path": "94czwi1",
  "domainUid": "9e2b3b57-5205-479f-9cfe-b2eeb135eff6",
  "urls": ["https://www.youtube.com/watch?v=GVTf9lLNnBU", "https://vms.dobroe22.keenetic.pro/#v1:0:=qemu%2F103:4:::::::"],
  "tags": []
}