GET {{url}}/api/v1/links
Authorization: Bearer {{$auth.token("access-token")}}

###

GET {{url}}/api/v1/user/links/6f7a1af1-03b1-493f-9e70-854136241c70
Authorization: Bearer {{$auth.token("access-token")}}

###

DELETE {{url}}/api/v1/user/links/f7d5833d-30b1-4065-91d4-2f2b8f8db11b
Authorization: Bearer {{$auth.token("access-token")}}

###

PUT {{url}}/api/v1/user/links/390a6128-25fc-4e73-af43-eb29540e8c2a
Authorization: Bearer {{$auth.token("access-token")}}
Content-Type: application/json

{
  "title": "gosha",
  "password": "1231",
  "tags": [ "daahs"]
}

###

POST {{url}}/api/v1/user/links
Authorization: Bearer {{$auth.token("access-token")}}
Content-Type: application/json

{
  "title": "gosha",
  "subdomain": "1231233",
  "domainUid": "6a8131a0-3848-43b7-a8d7-17e837bfb252",
  "url": "wg.dobroe22.keenetic.pro",
  "password": "123123",
  "tags": ["tester"]
}