GET {{url}}/api/v1/user/subdomains?domainUid=e481ae10-a860-45f3-be75-f537c108162b
Authorization: Bearer {{$auth.token("access-token")}}


##
GET {{url}}/api/v1/user/subdomains?domainUid=e481ae10-a860-45f3-be75-f537c108162b