GET {{url}}/api/v1/user/tags
Authorization: Bearer {{$auth.token("access-token")}}

###

PUT {{url}}/api/v1/user/tags/bober
Authorization: Bearer {{$auth.token("access-token")}}
Content-Type: application/json

{
  "title": "12"
}

###

DELETE {{url}}/api/v1/user/tags/daahs
Authorization: Bearer {{$auth.token("access-token")}}