GET http://localhost:2000/api/v1/links
Authorization: Bearer {{$auth.token("access-token")}}

###

GET http://localhost:2000/api/v1/links/ede725c6-aa14-44c5-823b-828fd881c79f
Authorization: Bearer {{$auth.token("access-token")}}

###

POST http://localhost:2000/api/v1/domains
Authorization: Bearer {{$auth.token("access-token")}}
Content-Type: application/json

{
    "title": "sh0.su"
}

###

GET http://localhost:2000/api/v1/domains
Authorization: Bearer {{$auth.token("access-token")}}